config/routes.rb
Rails.application.routes.draw do

  devise_for :teachers, :controllers => { omniauth_callbacks: "callbacks" }

  devise_scope :teacher do
    unauthenticated do
      root 'devise/registrations#new'
    end
  end


  root to: 'kithub#index'

  scope :api do
  	scope :v1 do
  		resources :teachers do 
        resources :contributions, only: [:index]
      end
      resources :students
      resources :courses
      resources :searches, only: [:index]
      resources :comments, only: [:create, :destroy]
      resources :assignments, only: [:create, :update, :destroy]
      resources :submissions, only: [:create, :index, :update]
      resources :lesson_plans, only: [:index, :create, :show, :update, :destroy] do
        resources :pull_requests, only: [:index, :create, :update]
        resources :additional_materials, only: [:index, :create]
        resources :lesson_plan_stars, only: [:create, :destroy]
        get "/export", to: "lesson_plans#export"
      end
      resources :flat_curves, only: [:create, :update, :destroy]
      resources :linear_curves, only: [:create, :update, :destroy]
      resources :additional_materials, only: [:destroy]
      resources :teacher_followings, only: [:index, :create, :destroy]
      resources :lesson_plan_contributors, only: [:index, :create]
      resources :lesson_plan_stars, only: [:index]
      resources :lesson_plan_days, only: [:create, :destroy]


      post "student_progress/fail/", to: "student_progress#fail"
      post "student_progress/exceptional/", to: "student_progress#exceptional"
      post "student_progress/fail_assignment/", to: "student_progress#fail_assignment"
      post "student_progress/exceptional_assignment/", to: "student_progress#exceptional_assignment"

      get "/gpas", to: "gpas_controller#index"
    end
 	end

  get '/gradebook', to: "gradebooks#index"
  get '/syllabi', to: 'syllabi#index'


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KitHub</title>
    <%= favicon_link_tag 'apple-fav.png' %>
    <%= csrf_meta_tags %>
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>

    <!-- d3 -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/4.2.8/d3.min.js"></script>

    <link href="https://fonts.googleapis.com/css?family=Cutive+Mono" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cabin+Sketch" rel="stylesheet">


    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>


  </head>

  <body <%= content_for :angular_app %> >
    <% if teacher_signed_in? %>

      <nav class="navbar navbar-light bg-faded" style="border-radius: 0px;">
        <%= image_tag "apple-fav.png", class: "pull-md-left brand-img" %>
        <a class="navbar-brand cabin-sketch-font" href="#" > <h1>KitHub</h1></a>
        <ul class="nav navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="<%= root_path %>" >Overview</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= gradebook_path %>" >Gradebook</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= syllabi_path %>" >Syllabi</a>
          </li>
        </ul>
        <% if controller_name == 'kithub' %>
          <div class="form-inline center-form" ng-controller="NavCtrl">
            <input class="form-control position-higher" type="text" ng-model="term" placeholder="Search">
            <select id="search-type-select" ng-model="searchType" class="selectpicker position-higher" style="width: 50px;">
              <option value="title">Title</option>
              <option value="content">Content</option>
              <option value="name">User</option>
            </select>
            <button class="btn btn-outline-success" ng-click="search()">Search</button>
          </div>
        <% end %>
        <ul class="nav navbar-nav pull-xs-right">
          <li class="nav-item">
            <a class="nav-link" href="<%= root_path %>"><%= current_teacher.first_name %></a>
          </li>
          <li class="nav-item">
            <%= link_to "Logout",  destroy_teacher_session_path, method: :delete, class: "nav-link" %>
          </li>
        </ul>

      </nav>
    <% end %>
    <div class="container-fluid">
      <%= yield %>
    </div>

  </body>
</html>